### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by hellagood9** [hellagood9/karumi#1]
- [x] #6 Initial commitment with application boilerplate
- [x] #7 **README.md** with the description of the project, technologies, etc..
- [x] #8 Add **Eslint** for js code quality and its script in package.json to run it
- [x] #9 Add **Prettier** for a consistent code formatting and its script in package.json to run it
- [x] #10 Add **Stylelint** for css code quality and its script in package.json to run it
- [x] #11 Add **Jest**, which displays the code coverage and its script in package.json to run it
- [x] #12 Add continuous integration with **Github Actions**. It must run Eslint, Prettier, Stylelint and Jest scripts. 
- [x] #13 Add **deployment in Netlify**. We are going to use Netlify serverless functions for the endpoints.
- [x] #35 Add **Editor configuration file**. Helps maintain consistent coding styles for multiple developers working on the same project.
- [x] #41 Add **Routing**. Create routes for navigation between public and private pages
- [x] #42 Add **Context**. Create a global state for an easier way to verify user status and pass methods to deeper Components
