### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by hellagood9** [hellagood9/karumi#2]
- [x] #14 **Layout** design
- [x] #15 **Layout** the form
- [x] #16 Implement the form (the login endpoint will be a serverless function)
- [x] #17 Form **Validation**
- [x] #18 **Error** management (endpoint not working, timeout, etc...)
- [x] #19 **Protected** page
- [x] #20 **Redirection** to protected page
- [x] #44 **Fix** for pending test files
