### ISSUE TITLE
Login Form Logic

### ISSUE THREAD

**Issue by hellagood9** [hellagood9/karumi#3]
- [x] #21 **Persistence** of jwt in browser storage after login
- [x] #22 **Recover** jwt from browser storage during application load
- [x] #23 Evaluate jwt against **validation** endpoint
- [x] #24 **Redirect** to login if jwt is not valid
- [x] #25 **Login** serverless endpoint
- [x] #26 **Logout** serverless endpoint
- [x] #27 **Me** serverless endpoint
